/// <reference types="expo/types" />

// NOTE: This file should not be edited and should be committed with your source code.
// It is generated by Expo and provides types for environment variables and Expo APIs.
